name:                regex-memo-lat
version:             0.1.0.0
github:              "0xd34df00d/regex-memo-lat"
license:             BSD-3-Clause
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2024 Georg Rudoy"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/0xd34df00d/regex-memo-lat#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- hashable
- megaparsec
- mtl
- parser-combinators
- unordered-containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  regex-memo-lat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regex-memo-lat
    - hspec
